project:
  type: website
  output-dir: docs

website:
  title: "nexus unl"
  favicon: "images/favicon.png"
  navbar:
    left:
      - about.qmd
      - the-team.qmd
      - events.qmd
      - google-form.qmd
  page-footer:
    left: "© 2026 Nexus UNL"
    center: "Nexus is a Student Election Group for the ASUN 2026 Election. Voting takes place on March 31st and April 1st."
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: fonts-and-styles/styles.css
    toc: true
    self-contained: false





