project:
  type: website
  output-dir: docs

website:
  title: "nexus unl"
  favicon: "Nexus UNL branding.png"
  navbar:
    left:
      - about.qmd
      - the-team.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



