---
title: "events"
---

::: {.section1}
# Alcohol Safety Presentation with UNL Campus Recreation

Monday, March 23

6:30pm in Avery 110

---

Alcohol Safety Presentation with Jon Gayer from UNL Campus Recreation

General Alcohol Program (15-30 minutes): Suitable for organization meetings. Includes an array of topics:
 
- **Standard Drinks and Pours** - this will look at what a standard drink is, talk about the dangers or not know what’s in a drink and practice on some of the favorite order drinks and how many standard drinks are in each pour. 
- **Safety Drinking Habits** -  Before a night out lets look at ways we can be safe.  Before going out to coming home.  We will take a look at prevention practices. 
- **The Science Behind Drinking** -  What does biphasic mean, how does alcohol effect your body and learn about, black out, alcohol poisoning and effects to the body. 
:::

::: {.section2 .spacer}
# Bystander Intervention with UNL CARE

Tuesday, March 24

6:00pm (location TBD)

---

Learn HOW to intervene in situations of sexual & dating violence, harassment, stalking, and identity-based crimes AND how to identify red flags that may signal intervention is needed!
:::

::: {.section1 .spacer}
# Meet Nexus UNL

Wednesday, March 25

6:00pm in Avery Hall 110

---

Meet Nexus members, learn about the Nexus campaign, and have your voice heard

:::

::: {.section2 .spacer}
# Daily Nebraskan Debate for ASUN Presidential Candidates

Thursday, March 26

6:00pm in Swanson Auditorium

---

Official ASUN Debate, hosted by the Daily Nebraskan - all are welcome to attend!

:::

::: {.section1 .spacer}
# Suicide Prevention with UNL CAPS

Friday, March 27

6:00pm (location TBD)

---

PREVENT SUICIDE is a 60-minute in-person training for University of Nebraska-Lincoln students, faculty and staff.

 - Increase Your Knowledge: learn the warning signs associated with suicide.
 - Name the Concerns and Ask: increase your confidence about communicating openly about suicide.
 - Provide Support and Resources: expand awareness about resources.
 - Connect To Help: learn how to take action when supporting others.

:::